mutation (
  $projectId: ID!
  $itemId: ID!
  $fieldId: ID!
  $fieldValue: String!
) {
  updateProjectV2ItemFieldValue(
    input: {
      projectId: $projectId
      itemId: $itemId
      fieldId: $fieldId
      value: { singleSelectOptionId: $fieldValue }
    }
  ) {
    clientMutationId
  }
}
